# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.17.2
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Exploring minima of Homsets
#
# This notebook explores the distribution of minima of homsets of supersingular elliptic curves with scalar level structure. To run it you will need the following python packages:

# %%
import pandas as pd, numpy as np, gzip
from matplotlib import pyplot as plt
from scipy.stats import norm
import math

# %% [markdown]
# The dataset was pre-generated. To generate a new one, install Sagemath and then run
#
# ```
# ./sample_mt.py <how_many> -p<char> -g<mod>
# ```
#
# This generates `<how_many>` random ideal classes of B_p,∞ with `p = <char>` and prints the 4 minima of the associated quadratic form, normalized by √p, and the associated Gram matrix modulo `<mod>`.

# %%
# parse the data into a Pandas dataframe
with gzip.open('p2e62_mega.csv.gz', 'rt') as f:
    # first line is a (useful) comment
    for i in range(1):
        print(next(f))
    idx = pd.MultiIndex.from_tuples([('λ', i) for i in range(4)] + [('g', r, c) for c in range(4) for r in range(c+1)],
                                    names=['type', 'row', 'col'])
    df = pd.read_csv(f, names=idx)

# %%
len(df)

# %% [markdown]
# ## Odd elements in the lattice
#
# We append the parity of the linear combinations of the basis vectors with coefficients in `[0,1]`

# %%
for i in range(1,16):
    lead = 3
    while not (1 << lead) & i:
        lead -= 1
    df[('parity', i, 0)] = df.g[lead][lead]
    low = i - (1 << lead)
    if low:
        df[('parity', i, 0)] += df[('parity', low, 0)]
        row = lead - 1
        while row >= 0:
            if (1 << row) & i:
                df[('parity', i, 0)] += df.g[row][lead]
            row -= 1
        df[('parity', i, 0)] %= 2

# %% [markdown]
# And then we count the ratio of odd elements in the box generated by the first 1, 2, 3, 4 minima

# %%
for i in range(1,5):
    df[('cum', i, 0)] = sum(df[('parity', x, 0)] for x in range(1, 1 << i)) / (1 << i)

# %% [markdown]
# Histograms confirm the predicted densities. Starting from the 3rd minimum, there is always at least 25% of odd elements.

# %%
df.cum.hist()

# %% [markdown]
# ## The minima
#
# Remember everything is divided by √p

# %%
df.λ.describe()

# %% [markdown]
# 1st and 4th minimum compared, log scale

# %%
np.log2(df[('λ', 0, None)]).hist(bins=1000, color='blue', log=True)
np.log2((df[('λ', 3, None)])).hist(bins=1000, color='red', alpha=0.5, log=True)

# %% [markdown]
# 2nd and 3rd

# %%
np.log2(df[('λ', 1, None)]).hist(bins=4000, color='blue', log=True)
np.log2(df[('λ', 2, None)]).hist(bins=4000, color='red', alpha=0.5, log=True)

# %% [markdown]
# Analyzing the quantiles in geometric progressoin (ratio 2) reveals a decently stable geometric progressions in the minima (`pct_change()` computes the "economist's ratio" between a row and its predecessor, so ratio is `1 + pct_change`)

# %%
df.λ.quantile([1-1/2**i for i in range(1,21)])

# %%
df.λ.quantile([1-1/2**i for i in range(1,21)]).pct_change()

# %% [markdown]
# By the eye test, $Pr(λ₃ > 2^{x/4} · m₃) < 1/2^{(x+1)}$, with $m$ being the median, looks like a pretty decent predictor

# %%
m = df.λ[2][np.nan].median()
[(len(df[df[('λ',2,None)] > m * np.sqrt(np.sqrt(2))**x]) / len(df) * 2**(x+1)) for x in range(0, 20)]

# %% [markdown]
# ### Hill estimator
#
# To argue about the correctness of the proposed hypotesis we cosider the [Hill estimator](https://en.wikipedia.org/wiki/Heavy-tailed_distribution#Hill.27s_tail-index_estimator), designed to estimate the behaviour of distributions with heavy upper tails. We search for $\alpha$ and $C$ such that
# $$ \mathbb P(X > x) = \bar F(x) \sim C x^{-\alpha} $$
# for large $x$, with $\alpha > 0$. Note: in the extreme value theory usually they write instead using $ \gamma = \frac{1}{\alpha}$.
#
# #### Definition
#
# Consider the order statistics of the sample
# $$
# X_{(1)} \le X_{(2)} \le \cdots \le X_{(n)}
# $$
#
# (funny word to say we use the sorted observations).
# Choose a tail size $k$, meaning that only the largest $k$ observations are used. The threshold is
#
# $$
# u = X_{(n-k)}.
# $$
#
# The Hill estimate of $\gamma = 1/\alpha$ is
#
# $$
# \hat\gamma(k)
# = \frac{1}{k} \sum_{i=1}^k
# \log\left(\frac{X_{(n-i+1)}}{u}\right).
# $$
#
# Then
#
# $$
# \hat\alpha(k) = \frac{1}{\hat\gamma(k)}.
# $$
#
# If the upper tail is close to Pareto with exponent $\alpha$, then $\hat\alpha(k)$ should be stable near $\alpha$ for a reasonable range of intermediate values of $k$.
#
# #### Choice of k
#
# The parameter $k$ is the main tuning choice.
#
# - If $k$ is too small, the estimate uses very few points and has high variance.
# - If $k$ is too large, the estimate includes non-tail observations and becomes biased.
# - The usual diagnostic is a Hill plot: plot $\hat\alpha(k)$ against $k$ and look for a stable plateau.
#
# From the theory (Theorem 3.2.2 of de Haan, Ferreira) we should choose $k$ as a function of the sample size $n$ so that as $n \to \infty$
# - $k(n) \to \infty$
# - $k(n)/n \to 0$ .
#
# In practice, we have a fixed sample size $n$, so we look for a range of $k$ that is not too small and not too large.
#
# For our data, good diagnostics were obtained for values such that $k/n$ ranges between about $0.01 \%$ and $1 \%$ of the sample size (`n > 1e6`).
# For larger k they started to behave differently, likely because it includes too much of the non-tail part of the distribution.
#
# #### Confidence Intervals
#
# Under standard regular variation assumptions, the Hill estimator has an asymptotic normal approximation. For $\hat\alpha$, a rough standard error is
#
# $$ \operatorname{se}(\hat\alpha) \approx \frac{\hat\alpha}{\sqrt{k}}. $$
#
# Thus an approximate 95% confidence interval is
#
# $$ \hat\alpha \pm 1.96 \frac{\hat\alpha}{\sqrt{k}}. $$
#
# This interval should be treated as a diagnostic, not as a final rigorous theorem for the finite-support distribution. It is useful because the finite cutoff is far outside the sampled range.
#
# #### Testing $\alpha = 4$
#
# For the null hypothesis
#
# $$
# H_0: \alpha = 4,
# $$
#
# we use
#
# $$ z = \frac{\hat\alpha - 4}{4 / \sqrt{k}}. $$
#
# The two-sided p-value is
#
# $$
# p = 2 \left(1 - \Phi(|z|)\right).
# $$
#
# This is again an asymptotic diagnostic. In our data, the p-values for $k$ between about $500$ and $20000$ did not reject $\alpha = 4$, while very large $k$ was less reliable.
#
# #### Estimating C
#
# If we fix $\alpha = 4$, then at the threshold $u = X_{(n-k)}$ we have
#
# $$
# \mathbb P(X > u) \approx \frac{k}{n}
# $$
#
# and the model says
#
# $$
# \mathbb P(X > u) \approx \frac{C}{u^4}.
# $$
#
# Therefore
#
# $$
# \hat C(k) = \frac{k}{n} u^4.
# $$
#
# If the model $\mathbb P(X > x) \sim C/x^4$ is valid over the observed tail range, then $\hat C(k)$ should also be reasonably stable as a function of $k$.
#

# %%
d = np.sort(df[('λ', 2, None)].dropna().to_numpy()) 
n = len(d) 
alpha0 = 4 
rows = [] 
perc_span = np.linspace(0.001, 0.1, 100) 

for perc in perc_span:
    k = math.ceil(perc*n)
    u = d[-k-1]
    tail = d[-k:]
    gamma_hat = np.mean(np.log(tail / u))
    alpha_hat = 1 / gamma_hat
    
    se = alpha_hat / math.sqrt(k)
    
    # Test H0: alpha = 4 using the Hill asymptotic normal approximation
    se0 = alpha0 / math.sqrt(k)
    z = (alpha_hat - alpha0) / se0
    p_value = 2 * (1 - norm.cdf(abs(z)))
    
    rows.append({
        "k": k,
        "perc": perc,
        "threshold": u,
        "alpha_hat": alpha_hat,
        "ci_low": alpha_hat - 1.96 * se,
        "ci_high": alpha_hat + 1.96 * se,
        "z_alpha_eq_alpha0": z,
        "p_value_alpha_eq_alpha0": p_value,
        "C_hat_alpha0": (k / n) * u**4,
    })

out = pd.DataFrame(rows)
out


# %%

title = 'Hill Estimator'
fig, axes = plt.subplots(3, 1, figsize=(8, 10), sharex=True)

ax = axes[0]
ax.plot(out["perc"], out["alpha_hat"], marker=".", linewidth=0.3)
ax.fill_between(out["perc"], out["ci_low"], out["ci_high"], alpha=0.2)
ax.axhline(alpha0, color="red", linestyle="--", linewidth=1, label=fr"$\alpha={alpha0}$")
ax.set_ylabel(r"$\hat\alpha$")
ax.set_title(title or "Hill tail diagnostics")
ax.legend()

ax = axes[1]
ax.plot(out["perc"], out["p_value_alpha_eq_alpha0"], marker=".", linewidth=0.3)
p = 0.05
ax.axhline(p, color="red", linestyle="--", linewidth=1, label=f"{ p = }")
ax.set_ylabel(fr"p-value for $\alpha={alpha0}$")
ax.set_ylim(-0.02, 1.02)
ax.legend()

ax = axes[2]
ax.plot(out["perc"], out["C_hat_alpha0"], marker=".", linewidth=0.5)
C_0 = 0.1
ax.axhline(C_0, color="red", linestyle="--", linewidth=1, label=f"{ C_0 = }")
ax.set_ylabel(fr"$\hat C$ assuming $\alpha={alpha0}$")
ax.set_xlabel("perc")
ax.legend()

plt.tight_layout()
plt.show()


# %% [markdown]
# We can run the same test for $\lambda_4$ with $\alpha_0 = 2$. The estimator seems to suggest that instead $\alpha \geq 2$.

# %%
d = np.sort(df[('λ', 3, None)].dropna().to_numpy()) 
n = len(d) 
alpha0 = 2
rows = [] 
perc_span = np.linspace(0.001, 0.3, 100) 

for perc in perc_span:
    k = math.ceil(perc*n)
    u = d[-k-1]
    tail = d[-k:]
    gamma_hat = np.mean(np.log(tail / u))
    alpha_hat = 1 / gamma_hat
    
    se = alpha_hat / math.sqrt(k)
    
    # Test H0: alpha = 4 using the Hill asymptotic normal approximation
    se0 = alpha0 / math.sqrt(k)
    z = (alpha_hat - alpha0) / se0
    p_value = 2 * (1 - norm.cdf(abs(z)))
    
    rows.append({
        "k": k,
        "perc": perc,
        "threshold": u,
        "alpha_hat": alpha_hat,
        "ci_low": alpha_hat - 1.96 * se,
        "ci_high": alpha_hat + 1.96 * se,
        "z_alpha_eq_alpha0": z,
        "p_value_alpha_eq_alpha0": p_value,
        "C_hat_alpha0": (k / n) * u**4,
    })

out = pd.DataFrame(rows)
out


# %%

title = 'Hill Estimator'
fig, axes = plt.subplots(3, 1, figsize=(8, 10), sharex=True)

ax = axes[0]
ax.plot(out["perc"], out["alpha_hat"], marker=".", linewidth=0.3)
ax.fill_between(out["perc"], out["ci_low"], out["ci_high"], alpha=0.2)
ax.axhline(alpha0, color="red", linestyle="--", linewidth=1, label=fr"$\alpha={alpha0}$")
ax.set_ylabel(r"$\hat\alpha$")
ax.set_title(title or "Hill tail diagnostics")
ax.legend()

ax = axes[1]
ax.plot(out["perc"], out["p_value_alpha_eq_alpha0"], marker=".", linewidth=0.3)
p = 0.05
ax.axhline(p, color="red", linestyle="--", linewidth=1, label=f"{ p = }")
ax.set_ylabel(fr"p-value for $\alpha={alpha0}$")
ax.set_ylim(-0.02, 1.02)
ax.legend()

ax = axes[2]
ax.plot(out["perc"], out["C_hat_alpha0"], marker=".", linewidth=0.5)
C_0 = 1.2
ax.axhline(C_0, color="red", linestyle="--", linewidth=1, label=f"{ C_0 = }")
ax.set_ylabel(fr"$\hat C$ assuming $\alpha={alpha0}$")
ax.set_xlabel("perc")
ax.legend()

plt.tight_layout()
plt.show()


# %%
